steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '$_ARTIFACTBUCKET/bootstrap/outputs.json', './iac/']

  - name: 'hashicorp/terraform:1.2.5'
    id: "infrastructure build"
    timeout: 1200s
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      x=`pwd`
      echo ${_STATEBUCKET} 
      cd iac
      export TF_VAR_project_id=${_PROJECT}
      export TF_VAR_project_number=${_PROJECTNUMBER}
      terraform init -reconfigure -backend-config="bucket=${_STATEBUCKET}"

      if [ ${_TYPE}  == "apply" ]
      then
        echo "Running Terraform Apply"
        terraform apply -lock=false -no-color -auto-approve || exit 1
      else
        terraform plan -lock=false
      fi

      terraform output -json > outputs.json
      
      cd $x

      echo $x

artifacts:
  objects:
    location: '$_ARTIFACTBUCKET/'
    paths: ['iac/outputs.json']

logsBucket: $_LOGBUCKET


