name: 'Plan Terraform IaC'

on:
  workflow_dispatch:
  pull_request:
     branches:
     - main
     
jobs:
  Terraform-IaC:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.CICD_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.CICD_SERVICE_ACCOUNT }}' 


      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      # Install the Google SDK and CLI
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Check Terraform Formatting'
        working-directory: ./iac
        shell: bash
        run: |-
          terraform fmt -recursive -check

 
      - name: Terraform Init 
        working-directory: ./iac
        run: |
          terraform init -backend-config="bucket=${{ secrets.STATE_BUCKET }}" -backend-config="prefix=dev"


      - name: Terraform Plan 
        working-directory: ./iac
        env: 
          TF_VAR_project_id: ${{ secrets.DEV_PROJECT_ID }}
          TF_VAR_project_number: ${{ secrets.DEV_PROJECT_NUMBER }}
        run: |
          terraform plan -lock=false
      
